spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.data-source-properties.useSSL=true
spring.datasource.hikari.data-source-properties.requireSSL=true






//============Befor adding aiven cloud ======================

//spring.application.name=event-registration-system
//spring.datasource.url=jdbc:mysql://localhost:3306/event_registration_system
//spring.datasource.username=
//spring.datasource.password=
//spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

//spring.jpa.hibernate.ddl-auto=update
//spring.jpa.show-sql=true
//spring.jpa.properties.hibernate.format_sql=true